language: go
go:
- 1.7
- 1.8
- master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
branches:
  only:
  - develop
  - master
install:
  - go get github.com/naoina/toml
  - go get github.com/keltia/flightaware-go/config
  - go get github.com/keltia/flightaware-go/flightaware

